@startuml
title FoodStack - Diagrama de Comunicação: Gerar Lista de Compras

skinparam shadowing false
skinparam defaultFontName Arial
skinparam ArrowColor Black
skinparam linetype ortho
skinparam nodesep 260
skinparam ranksep 180
skinparam object {
  BackgroundColor #FFF8CC
  BorderColor Black
}

object "Usuario" as Usuario
object "SistemaFoodStack" as Sistema
object "BancoDeDados" as Banco
object "Receita" as Receita
object "Estoque" as Estoque
object "ListaCompras" as Lista
object "Notificacao" as Notificacao

Notificacao -[hidden]down- Sistema
Usuario -[hidden]right- Sistema
Sistema -[hidden]right- Banco
Receita -[hidden]right- Estoque
Estoque -[hidden]right- Lista
Sistema -[hidden]down- Receita

Usuario -right-> Sistema : 1: solicitarLista(receitaID)\n6: exibirLista(itens)
Sistema -right-> Banco : 1.1: buscarReceita()\n1.1.1: receita()\n2.2: buscarEstoque()\n2.2.1: estoque()\n4: salvarLista()\n4.1: listaID()
Sistema -down-> Receita : 1.2: getIngredientes()\n1.2.1: ingredientes()
Sistema --> Estoque : 2: consultarDisponibilidade()\n2.1: itensDisponiveis()
Sistema --> Lista : 3: calcularFaltantes()\n3.1: listaCalculada()
Sistema -up-> Notificacao : 5: registrarEvento()\n5.1: eventoRegistrado()
@enduml
